# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ownerID', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('ownerName', models.CharField(max_length=20)),
                ('ownerLicense', models.CharField(max_length=50, null=True)),
                ('ownerPicture', models.ImageField(null=True, upload_to='img')),
                ('ownerPassword', models.CharField(max_length=20)),
                ('ownerEmail', models.EmailField(max_length=30)),
                ('ownerPhone', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Onwer',
        ),
    ]
