# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Model', '0003_delete_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=20)),
                ('ownerLicense', models.CharField(max_length=50, null=True)),
                ('ownerPicture', models.ImageField(null=True, upload_to='img')),
                ('ownerPassword', models.CharField(max_length=20)),
                ('ownerEmail', models.EmailField(max_length=30)),
                ('ownerPhone', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
